### ISSUE TITLE
Cannot ingest Refine project after check-in

### ISSUE THREAD

**Issue by ostephens** [k-int/gokb-phase1#90]
If you try to ingest a Refine project that has already been checked into GOKb, the 'estimate data changes' api call fails. If the project has not yet been checked in the estimate data changes call succeeds and the ingest goes ahead.

From Firebug:
[Error] SyntaxError: JSON Parse error: Unrecognized token '<'
    error (project-bundle.js, line 25324)
    fire (project-bundle.js, line 976)
    fireWith (project-bundle.js, line 1084)
    done (project-bundle.js, line 7792)
    callback (project-bundle.js, line 8502)

Content of request:

```
<!doctype html>
<!--

Copyright 2010, Google Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.
    * Neither the name of Google Inc. nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,           
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY           
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

-->

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=8;IE=9;chrome=1;">
    <title>Error - OpenRefine</title>
    <link rel="icon" type="image/png" href="images/favicon.png">
    <link rel="stylesheet" href="styles/common.less" />
  </head>
  <body>
    <div id="header">
      <a id="app-home-button" href="/"><img alt="OpenRefine" src="images/logo-openrefine-30.png" width="129" height="29" /></a>
    </div>
    <div id="body-info">
      <h1>Something went wrong!</h1>
      <h2>Cannot retrieve content from http://gokb.k-int.com/gokb/api/estimateDataChanges:</h2>  
  <pre class="errorstack">java.io.IOException: Cannot retrieve content from http://gokb.k-int.com/gokb/api/estimateDataChanges
    at com.k_int.gokb.refine.A_RefineAPIBridge.toAPI(A_RefineAPIBridge.java:336)
    at com.k_int.gokb.refine.A_RefineAPIBridge.postToAPI(A_RefineAPIBridge.java:285)
    at com.k_int.gokb.refine.commands.EstimateDataChanges.handleRequest(EstimateDataChanges.java:75)
    at com.k_int.gokb.refine.commands.EstimateDataChanges.doGet(EstimateDataChanges.java:35)
    at com.google.refine.RefineServlet.service(RefineServlet.java:170)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://gokb.k-int.com/gokb/api/estimateDataChanges
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
    at com.k_int.gokb.refine.A_RefineAPIBridge.toAPI(A_RefineAPIBridge.java:321)
    ... 26 more
</pre>
    </div>
  </body>
</html>
SyntaxError: JSON.parse: unexpected character
GOKb.defaultError(JSON.parse( jqXHR.responseText ));
project-bundle.js (line 25324)
```

**Comment by ostephens** [comment]
Resolved by using latest Refine client
